name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          # Add Python's user base `bin` directory to PATH
          echo "$(python -m site --user-base)/bin" >> $GITHUB_PATH

      # Step 4: Verify PythonAnywhere Installation
      - name: Verify PythonAnywhere Installation
        run: pythonanywhere --version

      # Step 5: Deploy to PythonAnywhere
      - name: Deploy to PythonAnywhere
        env:
          PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        run: |
          pythonanywhere ssh "cd ~/payments_summary/Payments_Summary && git pull || git clone https://github.com/gauthamgtg/Payments_Summary.git ~/payments_summary/Payments_Summary"
          pythonanywhere ssh "cd ~/payments_summary/Payments_Summary && pip install -r requirements.txt"
          pythonanywhere reload gauthamgtg.pythonanywhere.com
