name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Trigger deployment only on changes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Adjust if you're using a different Python version

      # Step 3: Install PythonAnywhere CLI
      - name: Install PythonAnywhere CLI
        run: pip install pythonanywhere

      # Step 4: Deploy to PythonAnywhere
      - name: Deploy to PythonAnywhere
        env:
          PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        run: |
          # Ensure the parent directory exists
          mkdir -p /home/gauthamgtg/payments_summary

          # Clone the repository if it doesn't exist, otherwise pull updates
          if [ -d "/home/gauthamgtg/payments_summary/Payments_Summary" ]; then
              cd /home/gauthamgtg/payments_summary/Payments_Summary
              git pull
          else
              git clone https://github.com/gauthamgtg/Payments_Summary.git /home/gauthamgtg/payments_summary/Payments_Summary
          fi

          # Change directory, install dependencies, and reload PythonAnywhere
          cd /home/gauthamgtg/payments_summary/Payments_Summary
          pip install -r requirements.txt
          pythonanywhere reload gauthamgtg.pythonanywhere.com
