name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Trigger deployment only on changes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Adjust if you're using a different Python version

      - name: Install PythonAnywhere CLI
        run: pip install pythonanywhere

      - name: Deploy to PythonAnywhere
        env:
          PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        run: |
          if [ -d "/home/gauthamgtg/payments_summary/Payments_Summary" ]; then
              cd /home/gauthamgtg/payments_summary/Payments_Summary && git pull
          else
              git clone https://github.com/gauthamgtg/Payments_Summary.git /home/gauthamgtg/payments_summary/Payments_Summary
          fi
          cd /home/gauthamgtg/payments_summary/Payments_Summary
          pip install -r requirements.txt
          pythonanywhere reload gauthamgtg.pythonanywhere.com