name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Deploy to PythonAnywhere
      - name: Deploy Code to PythonAnywhere
        env:
          PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        run: |
          curl -X POST https://www.pythonanywhere.com/api/v0/user/gauthamgtg/webapps/gauthamgtg.pythonanywhere.com/reload/ \
          -H "Authorization: Token $PA_API_TOKEN"
